apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # ..
  labels:
    # ..
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
# ..
      containers:
        - name: dataprd-rec-api
          image: 12345.ecr.amazon.com/dev-dataprd-admin:devel-a0aba94-202309061847
          imagePullPolicy: Always
          ports:
